name: TDD Tests
on:
  push:
    branches:    
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
   
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          
        ports:
          - 5432:5432
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    # TDD
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install libraries for PostgreSQL
        run: |
          apt-get update
          apt-get install -y gcc libpq-dev
          apt-get install -y curl
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      
      - name: Run nose unit test
        run: nosetests
        env:
          DATABASE_URI: "postgresql://postgres:postgres@postgres:5432/postgres"
